language: python
before_deploy:
  - make html
script:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}}
  keep-history: true
  repo: knewjade/tetris-knowledge
  local-dir: ./build/html/
  target-branch: master
